const $=id=>document.getElementById(id),video=$("video"),empty=$("empty"),channelsEl=$("channels"),catsEl=$("cats"),search=$("search");
let channels=JSON.parse(localStorage.getItem("iptvChannelsV3")||"[]"),favorites=JSON.parse(localStorage.getItem("iptvFavorites")||"[]"),selected=localStorage.getItem("iptvSelected"),category="All",hls=null;
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c])),initial=s=>(s||"?").trim()[0]?.toUpperCase()||"?";
function save(){localStorage.setItem("iptvChannelsV3",JSON.stringify(channels))}
function parseM3U(t){let o=[],m=null;for(let raw of t.replace(/\r/g,"").split("\n")){let l=raw.trim();if(!l)continue;if(l.startsWith("#EXTINF")){let k=l.indexOf(","),a=k>=0?l.slice(0,k):l,n=k>=0?l.slice(k+1).trim():"Unnamed",g=x=>(a.match(new RegExp(x+'="([^"]*)"','i'))||[])[1]||"";m={name:n||g("tvg-name")||"Unnamed",logo:g("tvg-logo"),category:g("group-title")||"General"}}else if(!l.startsWith("#")&&m){o.push({...m,url:l,id:l+"|"+m.name+"|"+o.length});m=null}}return o}
function render(){let cs=["All",...new Set(channels.map(c=>c.category))];if(!cs.includes(category))category="All";catsEl.innerHTML=cs.map(c=>`<button class="pill ${c==category?"on":""}" data-c="${esc(c)}">${esc(c)}</button>`).join("");catsEl.querySelectorAll("button").forEach(b=>b.onclick=()=>{category=b.dataset.c;render()});let q=search.value.toLowerCase(),list=channels.filter(c=>(category=="All"||c.category==category)&&(c.name+" "+c.category).toLowerCase().includes(q));$("count").textContent=`${channels.length} channel${channels.length==1?"":"s"}`;channelsEl.innerHTML=list.length?list.map(c=>`<button class="channel ${c.id==selected?"active":""}" data-id="${esc(c.id)}">${c.logo?`<img class="logo" src="${esc(c.logo)}" onerror="this.style.display='none'"><span class="fallback" style="display:none">${esc(initial(c.name))}</span>`:`<span class="fallback">${esc(initial(c.name))}</span>`}<span class="ct"><span class="cn">${favorites.includes(c.id)?"★ ":""}${esc(c.name)}</span><span class="cm">${esc(c.category)}</span></span></button>`).join(""):`<div style="padding:35px;text-align:center;color:#7e8998">${channels.length?"No matches.":"No playlist loaded."}</div>`;channelsEl.querySelectorAll(".channel").forEach(b=>b.onclick=()=>play(b.dataset.id))}
function play(id){let c=channels.find(x=>x.id==id);if(!c)return;selected=id;localStorage.setItem("iptvSelected",id);$("now").textContent=c.name;$("cat").textContent=c.category;$("status").textContent="Loading…";empty.style.display="none";$("fav").textContent=favorites.includes(id)?"★":"☆";render();if(hls){hls.destroy();hls=null}video.pause();video.removeAttribute("src");video.load();if(window.Hls&&Hls.isSupported()){hls=new Hls();hls.loadSource(c.url);hls.attachMedia(video);hls.on(Hls.Events.MANIFEST_PARSED,()=>{ $("status").textContent="Ready";video.play().catch(()=>{})});hls.on(Hls.Events.ERROR,(_,d)=>{if(d.fatal)$("status").textContent="Stream error"})}else if(video.canPlayType("application/vnd.apple.mpegurl")){video.src=c.url;video.onloadedmetadata=()=>{ $("status").textContent="Ready";video.play().catch(()=>{})}}else $("status").textContent="HLS unsupported"}
async function loadM3U(t,s){channels=parseM3U(t);if(!channels.length)throw Error("No channels found.");selected=null;save();$("pname").textContent=s;$("pmeta").textContent=`${channels.length} channels loaded`;localStorage.setItem("iptvPlaylistName",s);render()}
async function xtream(){let server=$("server").value.trim().replace(/\/+$/,""),u=$("user").value.trim(),p=$("pass").value;if(!server||!u||!p)throw Error("Enter server URL, username and password.");if(!/^https?:\/\//i.test(server))throw Error("Server URL must start with http:// or https://");let base=`${server}/player_api.php?username=${encodeURIComponent(u)}&password=${encodeURIComponent(p)}`,r=await fetch(base);if(!r.ok)throw Error(`Xtream API request failed (${r.status}). Provider may block browser/CORS.`);let info=await r.json();if(info.user_info&&String(info.user_info.auth)==="0")throw Error("Login rejected. Check your credentials.");r=await fetch(`${base}&action=get_live_streams`);if(!r.ok)throw Error(`Could not retrieve live channels (${r.status}).`);let s=await r.json();if(!Array.isArray(s))throw Error("Unexpected provider response.");channels=s.map((x,i)=>({id:`xt:${x.stream_id}:${i}`,name:x.name||`Channel ${x.stream_id}`,logo:x.stream_icon||"",category:x.category_name||"General",url:`${server}/live/${encodeURIComponent(u)}/${encodeURIComponent(p)}/${x.stream_id}.m3u8`}));save();$("pname").textContent="Xtream subscription";$("pmeta").textContent=`${channels.length} live channels`;localStorage.setItem("iptvPlaylistName","Xtream subscription");selected=null;render();let data=JSON.stringify({server,u,p});($("remember").checked?localStorage:sessionStorage).setItem("iptvXtream",data)}
function openDlg(){$("err").hidden=true;$("dlg").showModal();let x=localStorage.getItem("iptvXtream")||sessionStorage.getItem("iptvXtream");if(x)try{let d=JSON.parse(x);$("server").value=d.server;$("user").value=d.u;$("pass").value=d.p;$("remember").checked=!!localStorage.getItem("iptvXtream")}catch{}}
$("playlistBtn").onclick=openDlg;$("load").onclick=openDlg;$("close").onclick=()=>$("dlg").close();$("cancel").onclick=()=>$("dlg").close();
document.querySelectorAll(".tab").forEach(t=>t.onclick=()=>{document.querySelectorAll(".tab").forEach(x=>x.classList.remove("on"));document.querySelectorAll(".pane").forEach(x=>x.classList.remove("on"));t.classList.add("on");$(t.dataset.t).classList.add("on")});
$("form").onsubmit=async e=>{e.preventDefault();$("err").hidden=true;try{let a=document.querySelector(".tab.on").dataset.t;if(a=="xtream")await xtream();else if(a=="url"){let u=$("urlInput").value.trim(),r=await fetch(u);if(!r.ok)throw Error("Playlist request failed; provider may block CORS.");await loadM3U(await r.text(),u)}else if(a=="paste")await loadM3U($("textInput").value.trim(),"Pasted M3U");else{let f=$("fileInput").files[0];if(!f)throw Error("Choose an M3U file.");await loadM3U(await f.text(),f.name)}$("dlg").close()}catch(e){$("err").textContent=e.message;$("err").hidden=false}};
$("reload").onclick=()=>{let x=localStorage.getItem("iptvXtream")||sessionStorage.getItem("iptvXtream");if(x){let d=JSON.parse(x);$("server").value=d.server;$("user").value=d.u;$("pass").value=d.p;xtream().catch(e=>{$("status").textContent="Refresh failed"})}else openDlg()};
$("fav").onclick=()=>{if(!selected)return;favorites=favorites.includes(selected)?favorites.filter(x=>x!=selected):[...favorites,selected];localStorage.setItem("iptvFavorites",JSON.stringify(favorites));render()};$("fsBtn").onclick=()=>$("wrap").requestFullscreen?.();search.oninput=render;video.onplaying=()=>$("status").textContent="Playing";video.onwaiting=()=>$("status").textContent="Buffering…";$("pname").textContent=localStorage.getItem("iptvPlaylistName")||"No playlist loaded";render();